import typing

import torch

from qfeval_functions.random import is_fast
from qfeval_functions.random import rng


def randn(
    *size: int,
    dtype: typing.Optional[torch.dtype] = None,
    device: typing.Optional[torch.device] = None,
) -> torch.Tensor:
    r"""Returns a tensor filled with random numbers from a normal distribution
    with mean 0 and variance 1 (also called the standard normal distribution).

    Unlike :func:`torch.randn`, if the seed is fixed with
    :func:`qfeval_functions.random.seed`, the result must be reproducible on
    any device because random numbers are generated by a device-independent
    random number generator.  If the seed is set with ``fast=True``, this
    function falls back to :func:`torch.randn` for speed at the cost of such
    reproducibility.

    Args:
        *size (int):
            A sequence of integers defining the shape of the output tensor.
        dtype (torch.dtype, optional):
            The desired data type of the returned tensor.
            Default is ``torch.float32``.
        device (torch.device, optional):
            The desired device of the returned tensor.
            Default uses the current device.

    Returns:
        Tensor:
            A tensor of the given shape filled with standard normal random
            numbers.

    Example:

        >>> import qfeval_functions
        >>> with qfeval_functions.random.seed(1):
        ...     x = QF.randn(2, 3)
        >>> x
        tensor([[ 2.0468, -1.0365,  0.7300],
                [ 0.4158, -0.1923, -0.4909]])

    .. seealso::
        - :func:`randn_like`: Normal random tensor with the shape of another
          tensor.
        - :func:`rand`: Uniform random numbers on the interval [0, 1).
        - :func:`randint`: Uniform random integers.
    """
    if is_fast():
        return torch.randn(*size, dtype=dtype or torch.float32, device=device)
    v = rng().normal(0, 1, size)
    return torch.tensor(v, dtype=dtype or torch.float32, device=device)
