import typing

import torch

from qfeval_functions.random import is_fast
from qfeval_functions.random import rng


def rand(
    *size: int,
    dtype: typing.Optional[torch.dtype] = None,
    device: typing.Optional[torch.device] = None,
) -> torch.Tensor:
    r"""Returns a tensor filled with random numbers from a uniform distribution
    on the interval :math:`[0, 1)`.

    Unlike :func:`torch.rand`, if the seed is fixed with
    :func:`qfeval_functions.random.seed`, the result must be reproducible on
    any device because random numbers are generated by a device-independent
    random number generator.  If the seed is set with ``fast=True``, this
    function falls back to :func:`torch.rand` for speed at the cost of such
    reproducibility.

    Args:
        *size (int):
            A sequence of integers defining the shape of the output tensor.
        dtype (torch.dtype, optional):
            The desired data type of the returned tensor.
            Default is ``torch.float32``.
        device (torch.device, optional):
            The desired device of the returned tensor.
            Default uses the current device.

    Returns:
        Tensor:
            A tensor of the given shape filled with uniform random numbers
            in :math:`[0, 1)`.

    Example:

        >>> import qfeval_functions
        >>> with qfeval_functions.random.seed(1):
        ...     x = QF.rand(2, 3)
        >>> x
        tensor([[0.2407, 0.7296, 0.5584],
                [0.5268, 0.1469, 0.9072]])

    .. seealso::
        - :func:`rand_like`: Uniform random tensor with the shape of another
          tensor.
        - :func:`randn`: Standard normal random numbers.
        - :func:`randint`: Uniform random integers.
        - :func:`randperm`: Random permutation of integers.
    """
    if is_fast():
        return torch.rand(*size, dtype=dtype or torch.float32, device=device)
    v = rng().random(size)
    return torch.tensor(v, dtype=dtype or torch.float32, device=device)
