name: Check Translate Documentation

on:
  pull_request:
    branches: [master]
  schedule:
    - cron: "30 22 * * *"
  workflow_dispatch:

jobs:
  check-translate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Set up Python
        run: uv python install 3.13
      - name: Install dependencies
        run: uv sync --dev
      - name: Check translation
        run: |
          uv run make docs-plamo-translate-dry-run
