name: Auto Translate Documentation

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  translate-docs:
    runs-on: macos-latest # Apple Silicon required for plamo-translate

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # For pull_request events, checkout the head branch
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          # Fetch full history to enable proper git operations
          fetch-depth: 0
      - name: Check if running on Apple Silicon
        run: |
          if [ "$(uname -m)" != "arm64" ]; then
            echo "Error: This workflow requires Apple Silicon (arm64) runner"
            exit 1
          fi
          echo "✅ Running on Apple Silicon: $(uname -m)"
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Set up Python
        run: uv python install 3.13
      - name: Install dependencies
        run: uv sync --dev
      - name: Install plamo-translate-cli
        run: |
          uv run make docs-plamo-translate

      - name: Build documentation
        run: uv run make docs

      - name: Check for changes
        id: changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Check if there are any changes
          if git diff --quiet && git diff --staged --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
            git status
          fi

      - name: Comment on PR if no documentation changes
        if: github.event_name == 'pull_request' && steps.changes.outputs.has_changes == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const commentBody = `## 📚 Documentation Check Result

            ✅ **No documentation diff detected**

            The documentation build completed successfully with no changes.
            This indicates that:
            - All documentation is up to date
            - No translation updates were needed
            - Source files did not affect generated documentation

            ---

            🤖 Automated check by GitHub Actions  
            **Workflow**: Auto Translate Documentation  
            **Commit**: ${{ github.sha }}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            docs: Auto-translate documentation

            - Translated .po files using plamo-translate
          title: |
            docs: Auto-translate documentation
          body: |
            ## 📚 Auto-generated Documentation Translation

            This PR was automatically generated to translate documentation.

            ### Review Notes
            - Please review the translated content for accuracy
            - Check that technical terms are properly translated
            - Verify that code examples and formatting are preserved

            ---

            🤖 This PR was created automatically by GitHub Actions.

            **Triggered by**: ${{ github.event_name }}
            **Workflow**: Auto Translate Documentation
            **Runner**: ${{ runner.os }} (${{ runner.arch }})
          branch: auto-translate-docs/${{ github.run_number }}
          delete-branch: true
          labels: |
            documentation
            auto-translation
