name: Bump

on:
  create:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  bump-and-pr:
    name: Version Bump
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'release/') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install poetry
        run: pip install poetry
      - name: Bump version
        # TODO(masanori): Use uv to bump version
        run: echo "PR_TITLE=$(git branch --show-current | sed 's|release/||' | xargs poetry version)" >> "$GITHUB_OUTPUT"
        id: bump
      - name: Bump qfeval_functions.__version__
        run: git branch --show-current | sed 's|release/||' | xargs -I {} echo '__version__ = "{}"' > qfeval_functions/version.py
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          author: GitHub Actions <action@github.com>
          commit-message: ${{ steps.bump.outputs.PR_TITLE }}
          delete-branch: true
          branch-suffix: short-commit-hash
          title: ${{ steps.bump.outputs.PR_TITLE }}
